project-GAZA/GazaFront

.github/ISSUE_TEMPLATE/✅-feature.md
.github/ISSUE_TEMPLATE/🐛-bug.md
.github/PULL_REQUEST_TEMPLATE.md
package-lock.json
yarn.lock

📝 docs: 깃허브 pull rqquest 템플릿 설정하였습니다.

---

src/components/MessageComponent.tsx
src/components/component.style.ts
src/components/section_components/ShowComment.tsx
src/components/section_components/section.style.ts

- 피그마 디자인 대로 스크롤 바 스타일 수정을 진행하였습니다.

✨ feat: 응원 메세지 스크롤 바 디자인 시안 적용

---

src/app/_components/Sections/InputSection.tsx
src/app/_components/Sections/ShowGazaMap.tsx
src/app/_components/common/Main.tsx
src/app/_components/modal/Comment.tsx
src/app/_components/modal/ShareModal.tsx
src/hooks/useCustomToast.tsx
tsconfig.json

정해진 toast사용법을 분리시켜 재사용 가능하게 리팩토링을 진행했습니다.
진행 과정 중 tsconfig에서 catch의 Error를 추론하기 위해 type에 any를 명시할 수 있게 허용했습니다.
> closed #16

[recfactor] toast커스텀 훅

---

src/app/_components/modal/Donate.tsx
src/app/_components/modal/RegistModal.tsx
src/app/api/message/route.ts
src/types/props.ts
src/utils/api.ts
src/utils/usefull.ts

도네이트 백엔드 연결 - 백엔드 확인을 위해 바로 풀리퀘스트 수락합니다

[api]api연동 - 백엔드 연결때문에 바로 풀리퀘스트 수락

---

src/types/data.ts
src/utils/usefull.ts

[fix] lint error => 배포안되는 에러 수정

---

.eslintrc.json
src/app/_components/Sections/ExplainSectoin.tsx
src/app/_components/Sections/InputSection.tsx
src/app/_components/Sections/ShowComment.tsx
src/app/_components/Sections/section.style.ts
src/app/_components/common/Main.tsx
src/app/_components/modal/Comment.tsx
src/app/_components/modal/Donate.tsx
src/app/_components/modal/RegistModal.tsx
src/app/page.tsx
src/constants/index.ts
src/constants/korean.ts
src/types/data.ts
src/types/props.ts
src/utils/api.ts
src/utils/usefull.ts

- Component에서 사용하는 fetch코드 useFull로 분리
- 설명부분 변수로 초기화
- 관련 스크린샷
#16

[refactor] fetch코드 리팩토링, 설명부분 변수로 초기화(한글,영어대비)

---

src/app/_components/Sections/ShowGazaMap.tsx

[hotfix]댓글 퍼센트도 긴급 수정

---

.eslintrc.json
src/app/_components/MessageComponent.tsx
src/app/_components/Sections/ShowComment.tsx
src/app/_components/Sections/ShowGazaMap.tsx
tsconfig.json

[main] DEV사항 업데이트

---

src/app/api/message/route.ts

api/message/post부분 수정
- 관련 스크린샷

[hotfix]build에러 수정

---

.github/workflows/main.yml
.gitignore

- 작업 내용을 적어주세요
> ex. - CORS 허용 범위를 (/\*\*) URL 전체로 변경한다.
- 관련 스크린샷

[fix]gitignore+ workflow수정

---

src/app/page.tsx

- 작업 내용을 적어주세요
> ex. - CORS 허용 범위를 (/\*\*) URL 전체로 변경한다.
- 관련 스크린샷

[fix]builderror

---

src/app/gazaadmin/_components/DonateTable.tsx

[fix] gazaadmin긴급수정

---

next.config.js
src/app/api/donate/all/route.ts
src/app/api/message/count/route.ts
src/app/api/message/route.ts

api route로 잘 사용했다 싶었지만..
dev서버에서는 잘 호출되지만 build시에는
알수없는 이유로 donate/all이 호출이 안되서 원인을 몇시간 삽질 끝에 파악함
static site로 build가 되고있는것을 발견
그래서 
static으로 되어있는것에 force를 추가함
그랫더니 SSR로 잘 빌드됨!!!

[fix] build시 /donate/all, message/count - static으로 빌드되는거 수정

---

.eslintrc.json
.gitignore
package.json
src/component/HelloSection/Button.tsx
src/stories/Button.stories.tsx
tsconfig.json
yarn.lock

- 스토리북 설정과 스토리북 패키지를 추가했습니다.
eslint와 tsconfig에서 스토리북 관련된건 체크하고, 빌드하지 않습니다.

Joo hello section - 스토리북 추가했습니다.

---

build-storybook.log
package.json
yarn.lock

스토리북 배포 진행 작업
1. chromatic 패키지 설치
2.  yarn run chromatic --project-token={토큰값}
명령실행
<h1>즉시 머지하겠습니다!</h1>

[feat]StoryBook 배포준비 

---

package.json
yarn.lock

불필요 패키지 삭제 
toss payment 관련 패키지
channel talk 관련 패키지 삭제

[chore] remove not used packages

---

src/app/api/message/route.ts
src/utils/ipInfo.ts

[fe:log] api호출 에러 파악을 위한 로그 추가

---

src/app/api/message/route.ts
src/utils/ipInfo.ts
src/utils/serveraxios.ts

- 배포시 에러를 확인할 때 DEV를 거치는건 불편합니다.
- 따라서 개발단계에서는 DEV가 필요없다고 생각되서 삭제했습니다. 배포단계에서 브랜치 분리예정입니다. => 이슈등록하기
APIConnect FIx - back환경변수 변경 + 로그 추가

[fe:fix] APIConnect FIx - back환경변수 변경 + 로그 추가

---

src/utils/serveraxios.ts

- 작업 내용을 적어주세요
> ex. - CORS 허용 범위를 (/\*\*) URL 전체로 변경한다.
- 관련 스크린샷

[fe:fix] 환경변수 오타 수정

---

src/utils/dbController.ts

- 작업 내용을 적어주세요
> ex. - CORS 허용 범위를 (/\*\*) URL 전체로 변경한다.
- 관련 스크린샷

[fe:fix] api 로그확인중
